# Generated by Django 3.1.1 on 2022-05-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=200)),
                ('alternativa1', models.CharField(max_length=100)),
                ('alternativa2', models.CharField(max_length=100)),
                ('alternativa3', models.CharField(max_length=100)),
                ('alternativa4', models.CharField(max_length=100)),
                ('resposta', models.CharField(max_length=64)),
                ('explica', models.CharField(max_length=200)),
            ],
        ),
    ]
