# Generated by Django 3.1.1 on 2022-05-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='lastscore',
        ),
        migrations.AddField(
            model_name='questionario',
            name='imagem',
            field=models.CharField(default='sem imagem', max_length=200),
        ),
    ]
